/**
 * Generated by orval v7.13.2 ðŸº
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}
