/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostStatus } from './postStatus';

export type GetApiPostsParams = {
status?: PostStatus;
onlyEditable?: boolean;
};
