/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostStatus } from './postStatus';
import type { PostDtoPublishedAtUtc } from './postDtoPublishedAtUtc';

export interface PostDto {
  id: string;
  authorUserId: string;
  title: string;
  slug: string;
  excerpt: string;
  contentJson: string;
  contentHtml: string;
  contentText: string;
  coverImageMediaAssetId: string | null;
  coverImageUrl: string | null;
  status: PostStatus;
  seoTitle: string | null;
  seoDescription: string | null;
  publishedAtUtc: PostDtoPublishedAtUtc;
  createdAtUtc: string;
  updatedAtUtc: string;
}
