/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostDtoCoverImageMediaAssetId } from './postDtoCoverImageMediaAssetId';
import type { PostDtoCoverImageUrl } from './postDtoCoverImageUrl';
import type { PostStatus } from './postStatus';
import type { PostDtoSeoTitle } from './postDtoSeoTitle';
import type { PostDtoSeoDescription } from './postDtoSeoDescription';
import type { PostDtoPublishedAtUtc } from './postDtoPublishedAtUtc';

export interface PostDto {
  id: string;
  authorUserId: string;
  title: string;
  slug: string;
  excerpt: string;
  contentJson: string;
  contentHtml: string;
  contentText: string;
  coverImageMediaAssetId: PostDtoCoverImageMediaAssetId;
  coverImageUrl: PostDtoCoverImageUrl;
  status: PostStatus;
  seoTitle: PostDtoSeoTitle;
  seoDescription: PostDtoSeoDescription;
  publishedAtUtc: PostDtoPublishedAtUtc;
  createdAtUtc: string;
  updatedAtUtc: string;
}
