/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MediaAssetKind } from './mediaAssetKind';

export type PostApiMediaImagesParams = {
altText?: string;
kind?: MediaAssetKind;
postId?: string;
};
