/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UploadImageResponseSizeBytes } from './uploadImageResponseSizeBytes';
import type { UploadImageResponseWidth } from './uploadImageResponseWidth';
import type { UploadImageResponseHeight } from './uploadImageResponseHeight';
import type { UploadImageResponseAltText } from './uploadImageResponseAltText';

export interface UploadImageResponse {
  mediaAssetId: string;
  publicUrl: string;
  contentType: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sizeBytes: UploadImageResponseSizeBytes;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  width: UploadImageResponseWidth;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  height: UploadImageResponseHeight;
  altText: UploadImageResponseAltText;
}
