/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PostStatus } from './postStatus';

export interface UpsertPostRequest {
  title: string;
  slug: string;
  excerpt: string;
  contentJson: string;
  coverImageMediaAssetId: string | null;
  status: PostStatus;
  seoTitle: string | null;
  seoDescription: string | null;
}
