/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpsertPostRequestCoverImageMediaAssetId } from './upsertPostRequestCoverImageMediaAssetId';
import type { PostStatus } from './postStatus';
import type { UpsertPostRequestSeoTitle } from './upsertPostRequestSeoTitle';
import type { UpsertPostRequestSeoDescription } from './upsertPostRequestSeoDescription';

export interface UpsertPostRequest {
  title: string;
  slug: string;
  excerpt: string;
  contentJson: string;
  coverImageMediaAssetId: UpsertPostRequestCoverImageMediaAssetId;
  status: PostStatus;
  seoTitle: UpsertPostRequestSeoTitle;
  seoDescription: UpsertPostRequestSeoDescription;
}
