services:
  api:
    build:
      context: .
      dockerfile: deploy/api.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__postgres: ${ConnectionStrings__postgres}
    expose:
      - "80"
    networks:
      - niklabs-public

  web:
    build:
      context: .
      dockerfile: deploy/frontend.Dockerfile
    depends_on:
      - api
    expose:
      - "80"
    networks:
      - niklabs-public

networks:
  niklabs-public:
    external: true
