/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChangePasswordRequest,
  CsrfTokenResponse,
  ErrorResponse,
  LoginRequest
} from '.././models';

import { customFetch } from '../../services/api/client/custom-fetch';

export type postApiAuthLoginResponse200 = {
  data: void
  status: 200
}

export type postApiAuthLoginResponse401 = {
  data: ErrorResponse
  status: 401
}
    
export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
export type postApiAuthLoginResponseError = (postApiAuthLoginResponse401) & {
  headers: Headers;
};

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess | postApiAuthLoginResponseError)

export const getPostApiAuthLoginUrl = () => {


  

  return `/api/auth/login`
}

export const postApiAuthLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<postApiAuthLoginResponse> => {
  
  return customFetch<postApiAuthLoginResponse>(getPostApiAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}


export type postApiAuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postApiAuthLogoutResponse401 = {
  data: void
  status: 401
}
    
export type postApiAuthLogoutResponseSuccess = (postApiAuthLogoutResponse204) & {
  headers: Headers;
};
export type postApiAuthLogoutResponseError = (postApiAuthLogoutResponse401) & {
  headers: Headers;
};

export type postApiAuthLogoutResponse = (postApiAuthLogoutResponseSuccess | postApiAuthLogoutResponseError)

export const getPostApiAuthLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const postApiAuthLogout = async ( options?: RequestInit): Promise<postApiAuthLogoutResponse> => {
  
  return customFetch<postApiAuthLogoutResponse>(getPostApiAuthLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}

export type postApiAuthChangePasswordResponse204 = {
  data: void
  status: 204
}

export type postApiAuthChangePasswordResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiAuthChangePasswordResponse401 = {
  data: void
  status: 401
}
    
export type postApiAuthChangePasswordResponseSuccess = (postApiAuthChangePasswordResponse204) & {
  headers: Headers;
};
export type postApiAuthChangePasswordResponseError = ((postApiAuthChangePasswordResponse400 | postApiAuthChangePasswordResponse401)) & {
  headers: Headers;
};

export type postApiAuthChangePasswordResponse = (postApiAuthChangePasswordResponseSuccess | postApiAuthChangePasswordResponseError)

export const getPostApiAuthChangePasswordUrl = () => {


  

  return `/api/auth/change-password`
}

export const postApiAuthChangePassword = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<postApiAuthChangePasswordResponse> => {
  
  return customFetch<postApiAuthChangePasswordResponse>(getPostApiAuthChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordRequest,)
  }
);}


export type getApiAuthMeResponse200 = {
  data: void
  status: 200
}

export type getApiAuthMeResponse401 = {
  data: void
  status: 401
}
    
export type getApiAuthMeResponseSuccess = (getApiAuthMeResponse200) & {
  headers: Headers;
};
export type getApiAuthMeResponseError = (getApiAuthMeResponse401) & {
  headers: Headers;
};

export type getApiAuthMeResponse = (getApiAuthMeResponseSuccess | getApiAuthMeResponseError)

export const getGetApiAuthMeUrl = () => {


  

  return `/api/auth/me`
}

export const getApiAuthMe = async ( options?: RequestInit): Promise<getApiAuthMeResponse> => {
  
  return customFetch<getApiAuthMeResponse>(getGetApiAuthMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getApiAuthCsrfResponse200 = {
  data: CsrfTokenResponse
  status: 200
}

export type getApiAuthCsrfResponse401 = {
  data: void
  status: 401
}
    
export type getApiAuthCsrfResponseSuccess = (getApiAuthCsrfResponse200) & {
  headers: Headers;
};
export type getApiAuthCsrfResponseError = (getApiAuthCsrfResponse401) & {
  headers: Headers;
};

export type getApiAuthCsrfResponse = (getApiAuthCsrfResponseSuccess | getApiAuthCsrfResponseError)

export const getGetApiAuthCsrfUrl = () => {


  

  return `/api/auth/csrf`
}

export const getApiAuthCsrf = async ( options?: RequestInit): Promise<getApiAuthCsrfResponse> => {
  
  return customFetch<getApiAuthCsrfResponse>(getGetApiAuthCsrfUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}

