/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Niklabs.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  PostApiMediaImagesBody,
  PostApiMediaImagesParams,
  UploadImageResponse
} from '.././models';

import { customFetch } from '../../services/api/client/custom-fetch';

export type postApiMediaImagesResponse200 = {
  data: UploadImageResponse
  status: 200
}

export type postApiMediaImagesResponse400 = {
  data: void
  status: 400
}

export type postApiMediaImagesResponse401 = {
  data: void
  status: 401
}

export type postApiMediaImagesResponse403 = {
  data: void
  status: 403
}
    
export type postApiMediaImagesResponseSuccess = (postApiMediaImagesResponse200) & {
  headers: Headers;
};
export type postApiMediaImagesResponseError = (postApiMediaImagesResponse400 | postApiMediaImagesResponse401 | postApiMediaImagesResponse403) & {
  headers: Headers;
};

export type postApiMediaImagesResponse = (postApiMediaImagesResponseSuccess | postApiMediaImagesResponseError)

export const getPostApiMediaImagesUrl = (params?: PostApiMediaImagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/media/images?${stringifiedParams}` : `/api/media/images`
}

export const postApiMediaImages = async (postApiMediaImagesBody: PostApiMediaImagesBody,
    params?: PostApiMediaImagesParams, options?: RequestInit): Promise<postApiMediaImagesResponse> => {
    const formData = new FormData();
formData.append(`file`, postApiMediaImagesBody.file)

  return customFetch<postApiMediaImagesResponse>(getPostApiMediaImagesUrl(params),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}


